# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:

  - task: NuGetToolInstaller@1
    displayName: 'NuGet install'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '**/*.sln'

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.x'
    inputs:
      version: 3.1.x

  # - task: pjcollins.azp-utilities-boots.boots.Boots@1
  #   displayName: 'Install Mono'
  #   inputs:
  #     uri: 'https://download.mono-project.com/archive/6.12.0/macos-10-universal/MonoFramework-MDK-6.12.0.137.macos10.xamarin.universal.pkg'
        
  # - task: pjcollins.azp-utilities-boots.boots.Boots@1
  #   displayName: 'Install iOS'
  #   inputs:
  #     uri: 'https://download.visualstudio.microsoft.com/download/pr/e12e515d-da12-410b-acac-dd564a090b60/d0df6c6cfb219ebc3584bccc30e25bc5/xamarin.ios-14.16.0.5.pkg'
      
  # - script: '/bin/bash -c "echo ''##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]''/Applications/Xcode_$(XcodeVersion).app;sudo xcode-select --switch /Applications/Xcode_$(XcodeVersion).app/Contents/Developer"'
  #   displayName: 'Upgrade XCode'

  - task: XamariniOS@2
    inputs:
      solutionFile: '**/*.iOS.csproj'
      configuration: 'Release'
      buildForSimulator: true
      packageApp: false
