variables:
  - group: 'Secrets'

jobs:
    
# - job: Android
#   variables:
#     - group: 'Mobile Variables'
#   pool:
#     vmImage: 'macos-latest'

#   steps:
#   - task: NuGetToolInstaller@1
#     displayName: 'NuGet install'
#     inputs:
#       versionSpec: '5.10'

#   - task: NuGetCommand@2
#     displayName: 'NuGet restore'
#     inputs:
#       restoreSolution: '**/*.sln'

#   - task: UseDotNet@2
#     displayName: 'Use .NET Core SDK 3.1.x'
#     inputs:
#       packageType: 'sdk'
#       version: 3.1.x

#   - task: CmdLine@2
#     inputs:
#       script: 'mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./MVP.Android/MVP.Android.csproj /verbosity:normal /p:Configuration=Release'

- job: iOS
  variables:
    - group: 'Mobile Variables'
  pool:
    vmImage: 'macos-latest'
  steps:

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'MVP_FizoLabs_Dist.p12'
      certPwd: $(P12Password)
      deleteCert: true
      keychain: 'temp'
  
  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'AppStore.mobileprovision'

  - task: NuGetToolInstaller@1
    displayName: 'NuGet install'
    inputs:
      versionSpec: '5.10'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '**/*.sln'

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.x'
    inputs:
      packageType: 'sdk'
      version: 3.1.x

  - task: ios-bundle-version@1
    inputs:
      sourcePath: 'MVP.iOS/Info.plist'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildId)'
      printFile: true

  - task: CmdLine@2
    inputs:
      script: 'mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./MVP.iOS/MVP.iOS.csproj /verbosity:normal /p:Configuration=Release /p:Platform=iPhone /p:BuildIpa=true /p:OutputPath=$(Build.BinariesDirectory) /p:Codesignkey="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" /p:CodesignProvision=$(APPLE_PROV_PROFILE_UUID)'
    env:
      Secret_AuthClientId: $(AuthClientId)
      Secret_AuthSignatureHash: $(AuthSignatureHash)
      Secret_AppCenterProdiOSKey: $(AppCenterProdiOSKey)
      Secret_AppCenterProdAndroidKey: $(AppCenterProdAndroidKey)
      
  - task: CopyFiles@2
    inputs:
      contents: '**/*.ipa'
      sourceFolder: '$(Build.BinariesDirectory)' 
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'