trigger:
  branches:
    include:
      - main  
  paths:
    exclude:
    - ci.yml
    - cd.yml

variables:
  - group: 'Secrets'
  
jobs:
- job: Android
  pool:
    vmImage: 'macos-latest'

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'NuGet install'
    inputs:
      versionSpec: '5.10'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '**/*.sln'

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.x'
    inputs:
      packageType: 'sdk'
      version: 3.1.x

  - task: CmdLine@2
    inputs:
      script: 'mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./MVP.Android/MVP.Android.csproj /verbosity:normal /p:Configuration=Release'
    env:
      Secret_AuthClientId: $(AuthClientId)
      Secret_AuthSignatureHash: $(AuthSignatureHash)
      Secret_AppCenterProdiOSKey: $(AppCenterProdiOSKey)
      Secret_AppCenterProdAndroidKey: $(AppCenterProdAndroidKey)
      Secret_AppCenterDeviOSKey: $(AppCenterDeviOSKey)
      Secret_AppCenterDevAndroidKey: $(AppCenterDevAndroidKey)

- job: iOS
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: NuGetToolInstaller@1
    displayName: 'NuGet install'
    inputs:
      versionSpec: '5.10'

  - task: NuGetCommand@2
    displayName: 'NuGet restore'
    inputs:
      restoreSolution: '**/*.sln'

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK 3.1.x'
    inputs:
      packageType: 'sdk'
      version: 3.1.x

  - task: CmdLine@2
    inputs:
      script: 'mono /Applications/Visual\ studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll ./MVP.iOS/MVP.iOS.csproj /verbosity:normal /p:Configuration=Release'
    env:
      Secret_AuthClientId: $(AuthClientId)
      Secret_AuthSignatureHash: $(AuthSignatureHash)
      Secret_AppCenterProdiOSKey: $(AppCenterProdiOSKey)
      Secret_AppCenterProdAndroidKey: $(AppCenterProdAndroidKey)
      Secret_AppCenterDeviOSKey: $(AppCenterDeviOSKey)
      Secret_AppCenterDevAndroidKey: $(AppCenterDevAndroidKey)