name: CI on Pull Request

on: [push, pull_request]

jobs:   
  Android:
    runs-on: macos-latest
    steps:
    - uses: NuGet/setup-nuget@v1.0.2
    - name: Setup NuGet Sources
      run: nuget sources add -name "XamarinCommunityToolkit" -Source "https://pkgs.dev.azure.com/xamarin/public/_packaging/XamarinCommunityToolkitNightly/nuget/v3/index.json"
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd MVP.Android
        msbuild MVP.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
#   iOS:
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: iOS
#       run: |
#         nuget restore
#         msbuild MVP.iOS/MVP.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
