name: CI

on: [push, pull_request]

jobs:        
  Android:
    runs-on: macos-latest
    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        msbuild MVP.Android/MVP.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-latest
    steps:    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore
        msbuild MVP.iOS/MVP.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
