name: CI

on: [push, pull_request]

jobs:
        
  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      
    - name: Android
      run: |
        nuget restore
        cd MVP.Android
        msbuild MVP.Android.csproj /verbosity:normal /t:Rebuild /t:PackageForAndroid /t:SignAndroidPackage /p:Configuration=Debug 
    - uses: actions/upload-artifact@v2
      with:
        name: Android App
        path: MVP.Android/bin/Debug/com.fizolabs.mvp-Signed.apk
