name: CI

on: [push, pull_request]

jobs:        
#   Android:
#     runs-on: macos-11
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set default Xamarin SDK versions
#       run: |
#         $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=10.2
#     - name: Setup .NET Core SDK 5.0.x
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: '5.0.x'

#     - name: Install dependencies
#       run: nuget restore
    
#     - name: Build
#       run: msbuild MVP.Android/MVP.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  iOS:
    runs-on: macos-11
    steps:
      
      - name: Install dependencies 
        run: nuget restore

      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      
      - name: Build
        run: msbuild MVP/MVP.sln /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
